post:
  default_index_img: /img/example.png
  comments:
    enable: true
    type: utterances

utterances:
  repo: LxShine/lxshine.github.io
  issue_term: title
  label: utterances
  theme: github-light
  theme_dark: github-dark
  crossorigin: anonymous    


navbar:
  blog_title: Loexiang's blog

index:
  slogan:
    enable: true
    text: 「剑裁星河，码破天机」